version: "3.2"

services:
  assets-api:
    build:
      context: .
    image: frishi/assets-service-api
    container_name: assets-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 6000
    external_links:
      - nats
      - zookeeper
      - caddy
    networks:
      - main-network 

  assets:
    build:
      context: .
    image: frishi/assets-service
    container_name: assets-service
    env_file: docker-compose.env
    environment:
      SERVICES: assets
    external_links:
      - nats
      - zookeeper
      - caddy
    networks:
      - main-network

networks:
  main-network:
    external: true
