version: "3.2"

services:
  assets-api:
    build:
      context: .
    image: frishi/assets-service
    container_name: assets-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 6000
    external_links:
      - nats
      - zookeeper
    labels:
      - traefik.http.services.assets-api.loadbalancer.server.port=6000
      - traefik.enable=true
      - traefik.docker.network=gateway
      - traefik.http.routers.assets-api.service=assets-api@docker
      # - traefik.http.routers.posts-api.rule=Host(`services.rishighan.com`) && PathPrefix(`/api/v1/assets/`)
      - traefik.http.routers.assets-api.rule=Host(`localhost`) && PathPrefix(`/assets/api/`)
    networks:
      - gateway

  assets:
    build:
      context: .
    image: frishi/assets-service
    container_name: assets-service
    env_file: docker-compose.env
    environment:
      SERVICES: assets
    labels:
      - "traefik.enable=false"
    external_links:
      - nats
      - zookeeper
    networks:
      - gateway

networks:
  gateway: 
    external: true
